### ISSUE TITLE
Add a script that runs the server without provisioning

### ISSUE THREAD

**Issue by nadavsu** [beyond-io/roo.me#186]
**Is your feature request related to a problem? Please describe.**
Sometimes when running Vagrant, I would like to run the server without having to run the entire bootstrap script. The bootstrap script takes time and most of the time it does things which are meaningless (like trying to install libraries which are already installed), so I find myself copying the command which runs the server each time and running it manually.

**Describe the solution you'd like**
Creating a `run_server.sh` script which would include the command which runs the server, i.e. `nohup pipenv run python manage.py runserver 0.0.0.0:8000 &`

**Comment by nadavsu** [comment]
@1Oreo @simzacks @Omeramsc 
I would love your input on this.

**Comment by nadavsu** [comment]
Also, we could add a script for running Flake8 and pytest commands.

**Comment by AmitAharoni** [comment]
Issue closed.
