### ISSUE TITLE
Add base user

### ISSUE THREAD

**Issue by Micha546** [beyond-io/roo.me#28]
Need to add a base user from which the Seeker and Owner will "inherit" (or take the fields of the base user - not sure if inherit is the right term for Django models but thats the idea)

**Comment by Omeramsc** [comment]
Please add a description to the issue, and add acceptance criteria if you can. It'll make it easier to understand what exactly is needed. 
(The same goes for all future issues)

**Comment by Micha546** [comment]
Sorry, did not see your comment until now, adding description.
