### ISSUE TITLE
Learn mapping API

### ISSUE THREAD

**Issue by DanielMy777** [beyond-io/roo.me#32]
The skill of mapping API is needed in order to add the features
of radius-based apartment searching,
and also pin-pointing your location on a map for more comfortable use.
This will be obtained via GeoDjango[1].
[1]: https://docs.djangoproject.com/en/3.1/ref/contrib/gis/

**Comment by simzacks** [comment]
This is a complex function. My suggestion would be to make sure that the basic functionality works before trying to add mapping features.

**Comment by DanielMy777** [comment]
Complete
