### ISSUE TITLE
Update Flake8

### ISSUE THREAD

**Issue by AmitAharoni** [beyond-io/roo.me#45]
Currently the max line length in the Flake8 is 120.
There are very long lines in the migrations files.

We will update Flake8 tool max line length 260.

**Comment by simzacks** [comment]
That will negatively impact the rest of the code, as it won't enforce line length.
Maybe it makes more sense to turn off flake8 checking on autogenerated files?

https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html

**Comment by AmitAharoni** [comment]
Got it.
I will read and update.
